baseURL: https://europe.birki.io/
languageCode: en-us
title: europe
theme: PaperMod
params:
  defaultTheme: auto

  homeInfoParams:
    Title: G+L - 2017 Europe Journal 📓
    Content: A web version of Grant and Leah's 2017 Europe Journal. This is a collection of our thoughts, photos, and memories from our trip to Europe in 2017. We hope you enjoy reading it as much as we enjoyed writing it! Please note, our trip was a total of 55 days and after the "Budapest" incident, we pretty much lost track of writing in our journal.

  cover:
    linkFullImages: true

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
